% EEGLAB history file generated on the 02-Apr-2019
% ------------------------------------------------
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp3.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   3   7  10  39], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','pp3_ICAremoved','gui','off'); 
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp5.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2  11], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/pp5_ICAremoved.set','gui','off'); 
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp6.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2  56], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/pp6_ICAremoved.set','gui','off'); 
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp7.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   3   6  10  33  37], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 7,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/pp7_ICAremoved.set','gui','off'); 
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp9.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1  10  11  21  32  45], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 9,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/pp9_ICAremoved.set','gui','off'); 
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp10.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   9  11  21  47  51], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 11,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/pp10_ICAremoved.set','gui','off'); 
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp12.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 0, 1, 1);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2  18  26  40], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp12_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp14.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   3   7  28  31  33  34], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp14_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp15.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1  4], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp15_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp16.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   5   6   8   9  15  16  23  31  32  40], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp16_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp18.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 0, 1, 1);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   4   8  19  21  36], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp18_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp19.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   3   6  10  26], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp19_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp20.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   3   7  11  36  39  44], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp20_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_filteredforICApp21.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/Filtered_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
EEG = pop_runica(EEG, 'extended',1,'interupt','on');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_saveset( EEG, 'filename','Prob_reversal_ICA_ready_pp21.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
[EEG ALLEEG CURRENTSET] = eeg_retrieve(ALLEEG,1);
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:62] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   4   6   8  16  33], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp21_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp22.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 0, 1, 1);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1  35  36], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp22_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp23.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   4   8  15  16  21  25], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp23_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp24.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1  17  19  20  24  37], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp24_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp25.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [4   5   7   8  10  19  41], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 7,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp25_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp26.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   4   8  17  22  36], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp26_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp27.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   3   6  14  48  49], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp27_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp28.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1  2  3  5  7  8], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp28_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp29.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   3   5  14  54], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 7,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp29_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp30.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [3   9  17  18  19], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 9,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp30_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp31.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   7  14  29  31  63], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 11,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp31_ICAremoved.set','gui','off');
eeglab redraw;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp32.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [6  24  35  50  64], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp32_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp33.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   9  11  28  39], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp33_ICAremoved.set','gui','off');
EEG = pop_loadset('filename','Prob_reversal_ICA_ready_pp34.set','filepath','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:68] );
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1   2   6  12  16  36], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'savenew','/Volumes/Harde ploate/EEG_reversal_learning/EEG_data/ICA_files/pp34_ICAremoved.set','gui','off');
eeglab redraw;
